INFO 2023-11-04 21:40:21,234 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:40:21,234 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 21:40:30,323 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,323 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,343 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:40:30,343 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:40:30,347 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,347 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,356 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
ERROR 2023-11-04 21:40:30,356 user_service user_service.py 64 An exception occured in get_user:
Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 62, in get_user
    return self.user_model.objects.get(id=user_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 637, in get
    raise self.model.DoesNotExist(
spotify_analyzer.models.User.DoesNotExist: User matching query does not exist.
INFO 2023-11-04 21:41:23,418 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:23,418 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:24,313 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:24,313 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:30,715 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:30,715 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:41:31,579 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:41:31,579 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:42:38,797 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,797 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:42:38,799 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:42:38,799 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:42:38,806 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,806 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,807 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:42:38,807 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:09,806 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:43:09,806 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py changed, reloading.
INFO 2023-11-04 21:43:10,636 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:43:10,636 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 21:43:13,142 log log.py 241 Internal Server Error: /spotify/auth-code/
ERROR 2023-11-04 21:43:13,142 log log.py 241 Internal Server Error: /spotify/auth-code/
INFO 2023-11-04 21:43:27,986 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,986 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:43:27,987 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:43:27,987 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:43:27,994 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,994 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,995 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:43:27,995 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:37,412 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:45:37,412 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:45:45,782 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,782 user_service user_service.py 64 User does not exist
ERROR 2023-11-04 21:45:45,785 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
ERROR 2023-11-04 21:45:45,785 user_service user_service.py 46 An error occurred while creating a user: UNIQUE constraint failed: User.id
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: UNIQUE constraint failed: User.id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/user_service.py", line 40, in create_user
    return self.user_model.objects.create(**user_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1822, in execute_sql
    cursor.execute(sql, params)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: UNIQUE constraint failed: User.id
INFO 2023-11-04 21:45:45,791 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,791 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,792 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:45:45,792 user_service user_service.py 64 User does not exist
INFO 2023-11-04 21:50:23,623 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:50:23,623 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:50:24,569 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:50:24,569 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:51,823 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:51,823 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:52,324 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:52,324 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:53,508 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:53,508 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:52:53,932 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:52:53,932 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:53:01,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:53:01,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 21:53:01,999 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 21:53:01,999 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:03:59,632 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:03:59,632 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:00,687 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:00,687 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:06,073 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:06,073 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:06,918 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:06,918 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:09,255 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:09,255 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:04:10,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:04:10,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:23,480 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:23,480 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:23,972 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:23,972 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:29,199 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:29,199 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:29,974 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:29,974 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:35,374 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:35,374 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:05:36,263 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:05:36,263 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:52,698 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:52,698 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:53,573 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:53,573 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:54,891 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:54,891 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:55,780 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:55,780 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:06:59,127 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:06:59,127 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:00,029 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:00,029 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:04,401 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:04,401 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:07:05,296 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:07:05,296 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:00,750 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:00,750 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:01,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:01,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:07,043 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:07,043 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:07,868 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:07,868 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:13,260 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:13,260 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:14,133 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:14,133 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:18,506 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:18,506 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:11:19,457 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:11:19,457 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:42,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:42,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:42,528 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:42,528 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:46,738 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:46,738 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:47,183 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:47,183 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:57,479 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:57,479 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:12:58,459 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:12:58,459 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:13:01,830 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:13:01,830 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:13:02,707 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:13:02,707 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:14:26,296 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:14:26,296 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:14:26,798 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:14:26,798 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:39,968 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:39,968 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:40,807 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:40,807 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:42,108 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:42,108 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:42,954 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:42,954 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:58,656 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:58,656 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:15:59,514 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:15:59,514 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:02,849 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:02,849 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:03,704 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:03,704 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:12,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:12,182 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:16:13,097 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:16:13,097 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:09,937 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:09,937 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:10,829 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:10,829 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:13,144 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:13,144 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:14,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:14,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:18,419 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:18,419 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:19,243 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:19,243 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:21,574 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:21,574 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:22,433 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:22,433 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:24,751 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:24,751 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:25,609 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:25,609 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:26,905 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:26,905 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:27,787 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:27,787 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:34,234 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:34,234 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:17:35,106 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:17:35,106 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:19:14,966 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:19:14,966 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:19:15,580 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:19:15,580 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:30:05,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:30:05,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:30:06,368 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:30:06,368 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:53:51,260 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:53:51,260 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 22:54:02,049 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken()
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.getAccessToken() missing 1 required positional argument: 'user_id'
ERROR 2023-11-04 22:54:02,049 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken()
                  ^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.getAccessToken() missing 1 required positional argument: 'user_id'
INFO 2023-11-04 22:56:39,368 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:56:39,368 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:56:40,430 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:56:40,430 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:56:42,754 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:56:42,754 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:56:43,717 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:56:43,717 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 22:56:54,545 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 107, in getAccessToken
    if (self.isAccessTokenExpired(token=token, auth=auth)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 181, in isAccessTokenExpired
    return auth.is_token_expired(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/spotipy/oauth2.py", line 122, in is_token_expired
    return token_info["expires_at"] - now < 60
           ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
ERROR 2023-11-04 22:56:54,545 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 107, in getAccessToken
    if (self.isAccessTokenExpired(token=token, auth=auth)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 181, in isAccessTokenExpired
    return auth.is_token_expired(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/spotipy/oauth2.py", line 122, in is_token_expired
    return token_info["expires_at"] - now < 60
           ~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
INFO 2023-11-04 22:58:01,408 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:58:01,408 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 22:58:02,552 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 22:58:02,552 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:10:03,855 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:10:03,855 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 23:10:12,623 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 110, in getAccessToken
    if (self.isAccessTokenExpired(token=token_info, auth=auth)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 189, in isAccessTokenExpired
    return auth.is_token_expired(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/spotipy/oauth2.py", line 122, in is_token_expired
    return token_info["expires_at"] - now < 60
           ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
ERROR 2023-11-04 23:10:12,623 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 110, in getAccessToken
    if (self.isAccessTokenExpired(token=token_info, auth=auth)):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 189, in isAccessTokenExpired
    return auth.is_token_expired(token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/spotipy/oauth2.py", line 122, in is_token_expired
    return token_info["expires_at"] - now < 60
           ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
INFO 2023-11-04 23:14:08,602 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:14:08,602 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:14:09,711 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:14:09,711 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:14:15,101 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:14:15,101 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:14:15,928 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:14:15,928 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 23:14:34,502 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 125, in handleRefreshTokenChecking
    refresh_token = self.getRefreshToken()
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.getRefreshToken() missing 1 required positional argument: 'user_id'
ERROR 2023-11-04 23:14:34,502 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 125, in handleRefreshTokenChecking
    refresh_token = self.getRefreshToken()
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.getRefreshToken() missing 1 required positional argument: 'user_id'
INFO 2023-11-04 23:15:19,180 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:15:19,180 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:15:20,151 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:15:20,151 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 23:15:29,761 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 132, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.fetchAccessTokenWithRefreshToken() missing 2 required positional arguments: 'token' and 'user_id'
ERROR 2023-11-04 23:15:29,761 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 132, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SpotifyService.fetchAccessTokenWithRefreshToken() missing 2 required positional arguments: 'token' and 'user_id'
INFO 2023-11-04 23:16:43,007 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:16:43,007 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:16:44,107 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:16:44,107 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-04 23:16:49,710 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 132, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,user_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 154, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
ERROR 2023-11-04 23:16:49,710 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 113, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 132, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,user_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 154, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
INFO 2023-11-04 23:17:09,183 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:09,183 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:10,184 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:17:10,184 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:17:13,540 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:13,540 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:14,420 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:17:14,420 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:17:15,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:15,725 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:17:16,601 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:17:16,601 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:20:02,128 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:20:02,128 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-04 23:20:02,985 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-04 23:20:02,985 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:06,290 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:06,290 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:07,073 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:07,073 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:09,273 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:09,273 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:09,844 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:09,844 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:12,055 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:12,055 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:12,603 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:12,603 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:13,815 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:13,815 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:14,359 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:14,359 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:21,689 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:21,689 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:22,250 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:22,250 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:25,484 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:25,484 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:26,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:26,065 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:28,289 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:28,289 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:38:28,820 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:38:28,820 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:14,898 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:14,898 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:15,446 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:15,446 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:18,680 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:18,680 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:19,222 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:19,222 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:24,518 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:24,518 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:40:25,047 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:40:25,047 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-05 00:42:01,140 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
ERROR 2023-11-05 00:42:01,140 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
INFO 2023-11-05 00:44:01,074 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:01,074 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:01,629 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:01,629 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:12,069 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:12,069 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:12,605 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:12,605 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:15,835 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:15,835 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:16,442 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:16,442 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:20,724 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:20,724 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:21,276 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:21,276 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:31,729 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:31,729 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:44:32,252 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:44:32,252 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-05 00:44:49,789 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
ERROR 2023-11-05 00:44:49,789 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    refreshToken = token_info['refresh_token']
                   ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
INFO 2023-11-05 00:47:13,982 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:13,982 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:14,543 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:47:14,543 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:47:20,828 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:20,828 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:21,377 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:47:21,377 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:47:45,172 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:45,172 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:47:45,710 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:47:45,710 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-05 00:47:52,918 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    if token_info['refresh_token']:
      ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
ERROR 2023-11-05 00:47:52,918 log log.py 241 Internal Server Error: /spotify/auth-code/
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_view.py", line 34, in post
    spotify_service = SpotifyService(
                      ^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 43, in __init__
    accessToken = self.getAccessToken(user_id=user_id,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 109, in getAccessToken
    accessToken = self.handleRefreshTokenChecking(user_id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 128, in handleRefreshTokenChecking
    new_token = self.fetchAccessTokenWithRefreshToken(refresh_token,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py", line 152, in fetchAccessTokenWithRefreshToken
    if token_info['refresh_token']:
      ~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'refresh_token'
INFO 2023-11-05 00:49:34,487 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:49:34,487 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:49:35,021 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:49:35,021 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:49:47,470 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:49:47,470 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:49:48,011 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:49:48,011 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:51:05,758 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:51:05,758 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:51:06,094 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:51:06,094 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:52:08,161 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:52:08,161 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:52:08,680 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:52:08,680 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:52:11,909 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:52:11,909 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:52:12,625 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:52:12,625 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:58:05,565 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:58:05,565 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:58:06,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:58:06,102 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:58:07,323 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:58:07,323 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:58:07,850 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:58:07,850 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:59:19,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:59:19,059 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_service.py changed, reloading.
INFO 2023-11-05 00:59:19,582 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 00:59:19,582 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:18:07,077 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:18:07,077 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:19:33,619 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:19:33,619 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:19:54,507 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:19:54,507 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:20:23,307 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 05:20:23,307 autoreload autoreload.py 668 Watching for file changes with StatReloader
ERROR 2023-11-05 06:33:13,279 log log.py 241 Internal Server Error: /spotify/users/franserr/favorites
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_views/spotify_user_favorites_view.py", line 35, in post
    top_tracks = sp_track_service.get_monthly_tracks()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py", line 14, in get_monthly_tracks
    this_month_tracks = self.begin_build(term="long_term")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py", line 40, in begin_build
    df_with_audio = sp_utility.get_tracks(
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_tracks() missing 1 required positional argument: 'token_handler'
ERROR 2023-11-05 06:33:13,279 log log.py 241 Internal Server Error: /spotify/users/franserr/favorites
Traceback (most recent call last):
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django_injector/apps.py", line 169, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/franserr/opt/anaconda3/envs/tracker/lib/python3.12/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/views/spotify_views/spotify_user_favorites_view.py", line 35, in post
    top_tracks = sp_track_service.get_monthly_tracks()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py", line 14, in get_monthly_tracks
    this_month_tracks = self.begin_build(term="long_term")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py", line 40, in begin_build
    df_with_audio = sp_utility.get_tracks(
                    ^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_tracks() missing 1 required positional argument: 'token_handler'
INFO 2023-11-05 06:34:29,794 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:29,794 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:30,466 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:30,466 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:33,676 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:33,676 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:34,198 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:34,198 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:39,436 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:39,436 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:40,328 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:40,328 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:43,663 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:43,663 autoreload autoreload.py 266 /Users/franserr/Documents/course-work/port/new-portfolio/tracker/server/spotify_analyzer/services/spotify/spotify_track_service.py changed, reloading.
INFO 2023-11-05 06:34:44,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
INFO 2023-11-05 06:34:44,660 autoreload autoreload.py 668 Watching for file changes with StatReloader
